In [6]:
import time
from functools import wraps
import pandas as pd

df = pd.read_csv("..\\data\\data.csv")

time_data = {}
def timeit(func):
    @wraps(func)
    def wrapper(*args, **kwargs):
        start = time.perf_counter()
        result = func(*args, **kwargs)
        end = time.perf_counter()
        print(f"{func.__name__} took {end - start:.6f} seconds")
        time_data[func.__name__] = end - start
        return result
    return wrapper

@timeit
def std_deviation_long():
    data_ser = df['Calories'].dropna().tolist()
    mean = sum(data_ser)/len(data_ser)
    sq_deviation = [(data - mean)**2 for data in data_ser]
    std_deviation = (sum(sq_deviation)/len(sq_deviation))**0.5
    return std_deviation

@timeit
def std_deviation_inline():
    return (sum([(data - sum(df['Calories'].dropna().tolist())/len(df[
        'Calories'].dropna().tolist()))**2 for data in df['Calories'].dropna().tolist()])/len(
            [(data - sum(df['Calories'].dropna().tolist())/len(df[
        'Calories'].dropna().tolist()))**2 for data in df['Calories'].dropna().tolist()]))**0.5

@timeit
def std_deviation_inbuilt():
    return df['Calories'].std()

val1 = std_deviation_long()
val2 = std_deviation_inline()
val3 = std_deviation_inbuilt()

print(f"Time difference is: {abs(time_data['std_deviation_inline'] - time_data['std_deviation_long']):.6f} s or {round(abs(time_data['std_deviation_inline'] - time_data['std_deviation_long'])*100, 2)} %")
print(f"Standard Deviation (Long): {val1}")
print(f"Standard Deviation (Inline): {val2}")
print(f"Standard Deviation (Inbuilt): {val3}")

std_deviation_long took 0.000523 seconds
std_deviation_inline took 0.016111 seconds
std_deviation_inbuilt took 0.000251 seconds
Time difference is: 0.015588 s or 1.56 %
Standard Deviation (Long): 64.89439318359227
Standard Deviation (Inline): 64.89439318359227
Standard Deviation (Inbuilt): 66.00377941111952


### Source: https://www.w3schools.com/python/numpy/default.asp

## What is Numpy

- NumPy is a Python library used for working with arrays.
- It also has functions for working in domain like:
    - linear algebra
    - fourier transform
    - matrices.
- NumPy stands for Numerical Python.
- In Python we have lists that serve the purpose of arrays, but they are slow to process.
- NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.
- NumPy arrays are stored at one continuous place in memory unlike lists, so processes can access and manipulate them very efficiently.
- This behavior is called locality of reference in computer science.

## Numpy Array

In [7]:
import numpy as np

arr = np.array([1,3,5,6,8])
print(f'Array: {arr}\nArray Type: {type(arr)}')

Array: [1 3 5 6 8]
Array Type: <class 'numpy.ndarray'>


In [8]:
np.__version__

'2.1.3'

### 0-D arrays:
0-D arrays, or Scalars, are the elements in an array. Each value in an array is a 0-D array.

In [9]:
arr = np.array(40)
print(f"Array: {arr}\nDimension of array: {arr.ndim}")

Array: 40
Dimension of array: 0


### 1-D arrays:
An array that has 0-D arrays as its elements is called uni-dimensional or 1-D array.

In [10]:
arr = np.array([1,3,4,6,4])
print(f"Array: {arr}\nDimension of array: {arr.ndim}")

Array: [1 3 4 6 4]
Dimension of array: 1


### 2-D arrays:
An array that has 1-D arrays as its elements is called a 2-D array.
These are often used to represent matrix or 2nd order tensors.

In [11]:
arr = np.array([[1,3,4], [3, 6,4]])
print(f"Array: {arr}\nDimension of array: {arr.ndim}")

Array: [[1 3 4]
 [3 6 4]]
Dimension of array: 2


### 3-D arrays:
An array that has 2-D arrays (matrices) as its elements is called 3-D array.
These are often used to represent a 3rd order tensor.

In [34]:
arr = np.array([[[1, 3, 4], [3, 6, 4], [2, 3, 4]]])
print(f"Array: \n{arr}\nDimension of array: {arr.ndim}")

Array: 
[[[1 3 4]
  [3 6 4]
  [2 3 4]]]
Dimension of array: 3


### Creating an array with hgher dimentions

In [13]:
arr = np.array([1,2,3,4], ndmin=5)
print(f"Array: {arr}\nDimension of array: {arr.ndim}")

Array: [[[[[1 2 3 4]]]]]
Dimension of array: 5


### Accessing elements

In [35]:
# Accesing the elements in 1D array
arr = np.array([1,2,3,4,5])

print(f'first element: {arr[0]}\nlast element: {arr[-1]}\nsum: {arr[0] + arr[-1]}')

# Accesing the elements in 2D array
arr = np.array([[1,2,3], [4,5,6]])
print(f'\nelement from first row: {arr[0,2]}\nelement from second row: {arr[1,2]}\nsum: {arr[0,2] + arr[1,2]}')

# sum of rows
print(f'\nfirst row: {arr[0]}\nsecond row: {arr[1]}\nsum: {arr[0] + arr[1]}')


first element: 1
last element: 5
sum: 6

element from first row: 3
element from second row: 6
sum: 9

first row: [1 2 3]
second row: [4 5 6]
sum: [5 7 9]


In [36]:
# Accesing elements in 3D arrays

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr[0, 1, 2])
arr

6


array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

### array slicing

In [16]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print("1D array: ", arr[2:4], arr[::2])

# 2D arrays
arr = np.array([[1,2,3,4], [5,6,7,8]])
print("2D array: ", arr[1:2, 0:2])

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print("2D array: ", arr[0:2, 1:4])

1D array:  [3 4] [1 3 5 7]
2D array:  [[5 6]]
2D array:  [[2 3 4]
 [7 8 9]]


### Below is a list of all data types in NumPy and the characters used to represent them.
- i - integer
- b - boolean
- u - unsigned integer
- f - float
- c - complex float
- m - timedelta
- M - datetime
- O - object
- S - string
- U - unicode string
- V - fixed chunk of memory for other type ( void )

In [17]:
arr = np.array(['12,3,45,58'])
arr.dtype

dtype('<U10')

In [18]:
arr = np.array(['apple', 'banana', 'cherry'])
arr.dtype

dtype('<U6')

In [19]:
# Create an array with data type string
arr = np.array([1,2,4,5], dtype='S')
print(f'Array: {arr}\nData Type: {arr.dtype}')

Array: [b'1' b'2' b'4' b'5']
Data Type: |S1


In [20]:
arr = np.array([1, 2, 3, 4], dtype='i4')

print(arr)
print(arr.dtype)

[1 2 3 4]
int32


In [21]:
try:
    arr = np.array(['a', '2', '3'], dtype='i')
except ValueError as e:
    print(f"Failed to convert to given data type because {e}")

Failed to convert to given data type because invalid literal for int() with base 10: 'a'


### Converting the data types

In [22]:
arr = np.array([1.1, 2.1, 3.1])
new_arr = arr.astype("i")
print(new_arr)
print(new_arr.dtype)

[1 2 3]
int32


In [23]:
arr = np.array([1.1, 2.1, 3.1])
new_arr = arr.astype(int)
print(new_arr)
print(new_arr.dtype)

[1 2 3]
int64


In [24]:
arr = np.array([1, 0, 3])
new_arr = arr.astype(bool)
print(new_arr)
print(new_arr.dtype)

[ True False  True]
bool


### The Difference Between Copy and View
- The main difference between a copy and a view of an array is that the copy is a new array, and the view is just a view of the original array.
- The copy owns the data and any changes made to the copy will not affect original array, and any changes made to the original array will not affect the copy.
- The view does not own the data and any changes made to the view will affect the original array, and any changes made to the original array will affect the view.

In [25]:
# Copy
org_arr = np.array([1,2,3,4])
copy_arr = org_arr.copy()

org_arr[0] = 10
print(org_arr)
print(copy_arr)

[10  2  3  4]
[1 2 3 4]


In [26]:
# View
org_arr = np.array([1,2,3,4])
view_arr = org_arr.view()

org_arr[0] = 10
print(org_arr)
print(view_arr)

[10  2  3  4]
[10  2  3  4]


In [27]:
# Making changes in the view
org_arr = np.array([1,2,3,4])
view_arr = org_arr.view()

view_arr[0] = 10
print(org_arr)
print(view_arr)

[10  2  3  4]
[10  2  3  4]


### check if array owns the data
- Every NumPy array has the attribute base that returns None if the array owns the data.
- Otherwise, the base  attribute refers to the original object.

In [28]:
org_arr = np.array([1, 2, 3, 4, 5])
copy_arr = org_arr.copy()
view_arr = org_arr.view()

print(copy_arr.base)
print(view_arr.base)


None
[1 2 3 4 5]


### Shape of an array

In [29]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
arr.shape

(2, 4)

In [30]:
arr = np.array([[[1, 2, 3, 4], [5, 6, 7, 8]], [[5, 6, 7, 8], [2, 3, 4, 5]]])
arr.shape

(2, 2, 4)

In [31]:
arr = np.array([1, 2, 3, 4], ndmin=5)
arr.shape

(1, 1, 1, 1, 4)

### Reshaping arrays
- Reshaping means changing the shape of an array.
- The shape of an array is the number of elements in each dimension.
- By reshaping we can add or remove dimensions or change number of elements in each dimension.

In [32]:
# converting 1D array to 2D
d1_arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
d2_arr = arr.reshape(3,4)
d3_arr = arr.reshape(2,3,2)
print("2D array:\n", d2_arr)
print("\n3D array:\n", d3_arr)
print(f'\nOriginal Array Dimention: {d1_arr.ndim}')
print(f'D2 Array Dimension: {d2_arr.ndim}')
print(f'D3 Array Dimension: {d3_arr.ndim}')

ValueError: cannot reshape array of size 4 into shape (3,4)

In [ ]:
## returned array after reshaping is a view of original array
d2_arr.base

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

### Unknown Dimension
- You are allowed to have one "unknown" dimension.
- Meaning that you do not have to specify an exact number for one of the dimensions in the reshape method.
- Pass -1 as the value, and NumPy will calculate this number for you.

In [ ]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
new_arr = arr.reshape(3,2,-1)
new_arr

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

### Flattening the arrays
- Flattening array means converting a multidimensional array into a 1D array.
- We can use reshape(-1) to do this.

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr.reshape(-1)

array([1, 2, 3, 4, 5, 6])

In [ ]:
# we can use numpy to flatten list also
ls = [[1,2,3],[4,5,6]]
arr = np.array(ls)
arr.reshape(-1).tolist()

[1, 2, 3, 4, 5, 6]

### Iterating Arrays

In [ ]:
# 1D array
arr = np.array([1, 2, 3])
for i in arr:
    print(i)

1
2
3


In [ ]:
# 2D array
arr = np.array([[1, 2, 3], [4, 5, 6]])

# iterating through each dimensions
for i in arr:
    print(f'Dimension: {i}')

print("-"*50)

# iterating through each element of each dimension
for i in arr:
    for j in i:
        print(f'Dimension: {i} | element: {j}')

Dimension: [1 2 3]
Dimension: [4 5 6]
--------------------------------------------------
Dimension: [1 2 3] | element: 1
Dimension: [1 2 3] | element: 2
Dimension: [1 2 3] | element: 3
Dimension: [4 5 6] | element: 4
Dimension: [4 5 6] | element: 5
Dimension: [4 5 6] | element: 6


In [ ]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
for x in arr:
    print(f'Dimension: {x}')
    for y in x:
        print(f'Sub Dimension: {y}')
    print('-'*30)

Dimension: [[1 2 3]
 [4 5 6]]
Sub Dimension: [1 2 3]
Sub Dimension: [4 5 6]
------------------------------
Dimension: [[ 7  8  9]
 [10 11 12]]
Sub Dimension: [7 8 9]
Sub Dimension: [10 11 12]
------------------------------


### Iterating Arrays Using nditer()
- The function nditer() is a helping function that can be used from very basic to very advanced iterations. It solves some basic issues which we face in iteration, lets go through it with examples.
- In basic for loops, iterating through each scalar of an array we need to use n for loops which can be difficult to write for arrays with very high dimensionality.

In [ ]:
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
for x in np.nditer(arr):
    print(x, end=" | ")

1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 

In [ ]:
arr = np.array([1, 2, 3])
for x in np.nditer(arr, flags=['buffered'], op_dtypes='S'):
    print(x, type(x))

np.bytes_(b'1') <class 'numpy.ndarray'>
np.bytes_(b'2') <class 'numpy.ndarray'>
np.bytes_(b'3') <class 'numpy.ndarray'>


In [ ]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for x in np.nditer(arr[:, ::2]):
  print(x)

1
3
5
7


In [ ]:
# ndenumerate()
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for idx, item in np.ndenumerate(arr):
    print(f'index: {idx} | element: {item}')
    if idx == (1, 0):
        print("We are at first element of second dimension and it is", item)

index: (0, 0) | element: 1
index: (0, 1) | element: 2
index: (0, 2) | element: 3
index: (0, 3) | element: 4
index: (1, 0) | element: 5
We are at first element of second dimension and it is 5
index: (1, 1) | element: 6
index: (1, 2) | element: 7
index: (1, 3) | element: 8


### Joining Arrays

In [ ]:
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])

combined_arr = np.concatenate((arr1, arr2))
print(combined_arr)

[1 2 3 4 5 6 7 8]


In [ ]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
combined_arr = np.concatenate((arr1, arr2), axis=1)
combined_arr

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [ ]:
combined_arr = np.concatenate((arr1, arr2), axis=0)
combined_arr

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [ ]:
# Concanating two 1D arrays along different axis fails so we need to use "stack" for it
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])

stacked_arr = np.stack((arr1, arr2), axis=0)
stacked_arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
stacked_arr = np.stack((arr1, arr2), axis=1)
stacked_arr

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [ ]:
# hstack() to stack along rows
# same as np.concatenate((arr1, arr2))
np.hstack((arr1, arr2))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
# vstack() to stack along columns
# same as np.stack((arr1, arr2), axis=0)
np.vstack((arr1, arr2))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
# dstack() to stack along height, which is the same as depth
# same as np.stack((arr1, arr2), axis=1)
np.dstack((arr1, arr2))

array([[[1, 5],
        [2, 6],
        [3, 7],
        [4, 8]]])

### Splitting Arrays

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6])
np.array_split(arr, 2)

[array([1, 2, 3]), array([4, 5, 6])]

In [ ]:
np.array_split(arr, 3)

[array([1, 2]), array([3, 4]), array([5, 6])]

In [ ]:
# If the array has less elements than required, it will adjust from the end accordingly
np.array_split(arr, 4)

[array([1, 2]), array([3, 4]), array([5]), array([6])]

In [ ]:
split_list = np.array_split(arr, 3)
print(f'Split List: {split_list}\nSplit List Type: {type(split_list)}')
print(f'First element of split list: {split_list[0]}, type: {type(split_list[0])}')
print(f'First element of split list: {split_list[1]}, type: {type(split_list[1])}')

Split List: [array([1, 2]), array([3, 4]), array([5, 6])]
Split List Type: <class 'list'>
First element of split list: [1 2], type: <class 'numpy.ndarray'>
First element of split list: [3 4], type: <class 'numpy.ndarray'>


In [ ]:
# 2D array
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])
print(np.ndim(arr))
np.array_split(arr, 2)

2


[array([[1, 2],
        [3, 4],
        [5, 6]]),
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]])]

In [ ]:
np.array_split(arr, 3)

[array([[1, 2],
        [3, 4]]),
 array([[5, 6],
        [7, 8]]),
 array([[ 9, 10],
        [11, 12]])]

In [ ]:
np.array_split(arr, 6)

[array([[1, 2]]),
 array([[3, 4]]),
 array([[5, 6]]),
 array([[7, 8]]),
 array([[ 9, 10]]),
 array([[11, 12]])]

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])
np.array_split(arr, 3, axis=1)

[array([[ 1],
        [ 4],
        [ 7],
        [10],
        [13],
        [16]]),
 array([[ 2],
        [ 5],
        [ 8],
        [11],
        [14],
        [17]]),
 array([[ 3],
        [ 6],
        [ 9],
        [12],
        [15],
        [18]])]

### Searching Arrays
- You can search an array for a certain value, and return the indexes that get a match.
- To search an array, use the where() method.

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 4, 4])
np.where(arr == 4)

(array([3, 5, 6]),)

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 4], [4, 3, 5]])
np.where(arr == 4)

(array([1, 1, 2]), array([0, 2, 0]))